plugins {
    id 'com.android.application'
}

android {
    compileSdk 36
    namespace "com.siebeprojects.samples.keyboardheight"

    defaultConfig {
        minSdk 21
        targetSdk 36
        versionName "1.1.0"
        versionCode 1100
        applicationId "com.siebeprojects.samples.keyboardheight"
    }

    lint {
        abortOnError false
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
}
